def choose_lang(lang):
    if lang == 'ja':
        lang_set = {
            "w_install_tab_title" : "インストール",
            "w_install_tab_link1" : "OpenRadiossのインストール",
            "w_install_tab_link2" : "Gmshのインストール",
            "w_install_tab_link3" : "VSCodeのインストール",
            "w_install_tab_link4" : "ParaViewのインストール",
            "w_pass_tab_title" : "パス入力",
            "w_passDocLabel1" : "パスタブの設定について",
            "w_IDirLabel1" : "OpenRadiossのフォルダパス",
            "w_IDirLabel2" : "Gmshのフォルダパス",
            "w_IDirLabel3" : "VSCodeのフォルダパス",
            "w_IDirLabel4" : "ParaViewのフォルダパス",
            "w_mesh_tab_title" : "メッシュ作成",
            "w_meshDocLabel1" : "メッシュタブの操作について",
            "w_mesh_tab_IDirLabel1" : "Gmshの起動",
            "w_mesh_tab_IDirButton3" : "Gmsh起動", 
            "w_input_tab_title" : "インプット作成",
            "w_input_tab_workdir_label" : "作業フォルダのパス",
            "w_input_tab_load_sample_label": "サンプルファイルのロード",
            "w_input_tab_Label1" : "インプット入力タブの操作について",
            "w_input_tab_IDirLabel1" : "VSCodeの起動",
            "w_input_tab_IDirButton1" : "VSCode起動",
            "w_calc_tab_title" : "計算実行",
            "w_calcDocLabel1" : "計算実行タブの操作について",
            "w_calc_tab_IFileLabel1" : "0000ファイルの指定",
            "w_calc_tab_IFileLabel2" : "0001ファイルの指定",
            "w_calc_tab_parallel_cpus_label" : "並列CPU数",
            "w_calc_tab_precision_label" : "精度選択",
            "w_calc_tab_stack_size_label" : "スタックサイズ",
            "w_calc_tab_IFileLabel3" : "OpenRadiossの実行",
            "w_calc_tab_IFileButton3" : "計算実行",
            "w_post_tab_title" : "結果処理",
            "w_postDocLabel1" : "結果処理タブの操作について",
            "w_post_tab_IDirLabel2" : "ParaViewの起動",
            "w_post_tab_IDirButton2" : "ParaView起動",
            'w_precision1' : '単精度',
            'w_precision2' : '倍精度',
            'w_refer' : '参照',
            'path_doc_calc_tab' : "calc_tab_win.html",
            'path_doc_gmsh_install' : "gmsh_install_win.html",
            'path_doc_input_tab' : "input_tab_win.html",
            'path_doc_mesh_tab' : "mesh_tab_win.html",
            'path_doc_openradioss_install' : "openradioss_install_win.html",
            'path_doc_paraview_install' : "paraview_install_win.html",
            'path_doc_path_setting' : "path_setting_win.html",
            'path_doc_post_tab' : "post_tab_win.html",
            'path_doc_vscode_install' : "vscode_install_win.html",
        }
        return lang_set
    elif lang == 'en':
        lang_set = {
            "w_install_tab_title" : "Install",
            "w_install_tab_link1" : "Install OpenRadioss",
            "w_install_tab_link2" : "Install Gmsh",
            "w_install_tab_link3" : "Install VSCode",
            "w_install_tab_link4" : "Install ParaView",
            "w_pass_tab_title" : "Path entry",
            "w_passDocLabel1" : "About the operation of the path tab(ja)",
            "w_IDirLabel1" : "OpenRadioss folder path",
            "w_IDirLabel2" : "Gmsh folder path",
            "w_IDirLabel3" : "VSCode folder path",
            "w_IDirLabel4" : "ParaView folder path",
            "w_mesh_tab_title" : "Mesh Creation",
            "w_meshDocLabel1" : "About the operation of the mesh tabs(ja)",
            "w_mesh_tab_IDirLabel1" : "Gmsh",
            "w_mesh_tab_IDirButton3" : "Launch", 
            "w_input_tab_title" : "Input creation",
            "w_input_tab_workdir_label" : "Working folder path",
            "w_input_tab_load_sample_label": "Loading sample files",
            "w_input_tab_Label1" : "About the operation of the input input tab(ja)",
            "w_input_tab_IDirLabel1" : "VSCode",
            "w_input_tab_IDirButton1" : "Launch",
            "w_calc_tab_title" : "Calculation",
            "w_calcDocLabel1" : "About the operation of the Calculation Run tab(ja)",
            "w_calc_tab_IFileLabel1" : "Designation of 0000 files",
            "w_calc_tab_IFileLabel2" : "Designation of 0001 files",
            "w_calc_tab_parallel_cpus_label" : "Number of parallel CPUs",
            "w_calc_tab_precision_label" : "Precision selection",
            "w_calc_tab_stack_size_label" : "Stack size",
            "w_calc_tab_IFileLabel3" : "OpenRadioss",
            "w_calc_tab_IFileButton3" : "Run calculation",
            "w_post_tab_title" : "Result",
            "w_postDocLabel1" : "About the operation of the Result Processing tab(ja)",
            "w_post_tab_IDirLabel2" : "ParaView",
            "w_post_tab_IDirButton2" : "Launch",
            'w_precision1' : 'Single',
            'w_precision2' : 'Double',
            'w_refer' : 'Browse',
            'path_doc_calc_tab' : "calc_tab_win_en.html",
            'path_doc_gmsh_install' : "gmsh_install_win_en.html",
            'path_doc_input_tab' : "input_tab_win_en.html",
            'path_doc_mesh_tab' : "mesh_tab_win_en.html",
            'path_doc_openradioss_install' : "openradioss_install_win_en.html",
            'path_doc_paraview_install' : "paraview_install_win_en.html",
            'path_doc_path_setting' : "path_setting_win_en.html",
            'path_doc_post_tab' : "post_tab_win_en.html",
            'path_doc_vscode_install' : "vscode_install_win_en.html",
        }
        return lang_set